version: "3.9"
services:
  gpu:
    build: .
    ports:
      - "8284:80"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: sh -c "nvidia-smi && npm run start"
